#!/usr/bin/ruby

## zinsser.rb --- Clean up English text
#
# Copyright (c) 2011 Art Taylor 
#
# Filename: zinsser.rb
# Author: Art Taylor <art@arttaylor.com>
# Version: 1.0
# Keywords: Zinsser, On Writing Well, English text
#
# [Commentary]
#
# This is a simple script to apply recommendations from On Writing Well by William Zinsser
# http://www.amazon.com/exec/obidos/ASIN/0060891548/reesesweb <- affiliate link
#
# Removes or replaces overused phrases with clearer and less affected alternatives.
#
# Usage: zinsser.rb < file or zinsser file
#
#
# [License]
#
# This software is provided 'as-is', without any express or implied
# warranty.  In no event will the author be held liable for any
# damages arising from the use of this software.
#
# Permission is granted to anyone to use this software for any
# purpose, including commercial applications, and to alter it and
# redistribute it freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must
#    not claim that you wrote the original software. If you use this
#    software in a product, an acknowledgment in the product
#    documentation would be appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must
#    not be misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source
#    distribution.
#
# Note that this license is borrowed from zlib via nullsoft.
#
# Written 10-Apr-2011, Oakland, CA
#


rule_hash = eval DATA.read()

text = ARGF.readlines()

def split_into_sentences (paragraph)
  sentences = []
  fragment = ""
  paragraph.each_char { | character |
    if character == "." or character == "?"
      sentences << (fragment + character.to_s)
      fragment = ""
    else
      fragment += character.to_s
    end
  }

  sentences
end


def fix_sentence (sentence, rule_hash)
  rule_hash.each_key {|key|
    i = sentence.index(/#{Regexp.escape(key)}/i)
    unless i.nil?
      sentence.gsub!(/#{Regexp.escape(key)}/i, rule_hash[key])
      if rule_hash[key] == ""
        if i == 0
          i = 1
        end
        if sentence[i-1,2] == ",,"
          sentence.gsub!(/,,/, "") #in case we just nuked a parenthetical phrase
        else
          sentence.slice!(i-1, 1) #Eliminate space after the whole we just punched
        end
        sentence.gsub!(/,\./, ".") #in case we just nuked a parenthetical phrase at the end of a sentence
      end
    end
  }
  sentence.strip
end


puts text.collect{|paragraph| split_into_sentences(paragraph)}.
         collect{|sentences| sentences.collect{|sentence| fix_sentence(sentence, rule_hash)}.join("  ") + "\n"
}.join

__END__
Hash[
"(^order of) magnitude" => "size",
", like," => "",
", of course," => "",
"12 midnight" => "midnight",
"12 noon" => "noon",
"HIV virus" => "HIV",
"Honestly," => "",
"I'm able to" => "I can",
"a big fan of" => "a fan of ",
"a bit more" => "more",
"a bit of" => "some",
"a considerable amount of" => "",
"a pretty" => "a",
"a rather" => "a",
"a slew of" => "",
"absolutely" => "",
"access:verb" => "get",
"achieve" => "get",
"act to" => "",
"actual experience" => "experience",
"actually" => "",
"added bonus" => "bonus",
"address the problem" => "solve the problem",
"address this problem" => "solve this problem",
"adjust" => "change",
"adjustment" => "change",
"advance notice" => "notice",
"advance planning" => "planning",
"advance reservations" => "reservations",
"advance warning" => "warning",
"aforementioned" => "",
"after all is said and done" => "",
"all of a sudden" => "suddenly",
"all of the" => "all the",
"all of these" => "these",
"all things considered" => "",
"all time record" => "record",
"all-time record" => "record",
"allow me to" => "i will",
"almost all" => "most",
"almost certainly" => "",
"almost completely" => "almost",
"almost entirely" => "mostly",
"almost everyone" => "most people",
"almost never" => "seldom",
"along the lines of" => "like",
"already exist" => "exist",
"am able to" => "can",
"ameliorate" => "improve",
"amongst" => "among",
"amounts to" => "is",
"an estimated" => "about",
"an individual" => "a man or woman",
"analogous" => "similar",
"and also" => "and",
"and even worse," => "worse,",
"anticipate" => "expect",
"any and all" => "all",
"any given" => "any",
"anything resembling" => "",
"apparent" => "",
"apparently" => "",
"append" => "add",
"are able to" => "can",
"are now wondering" => "are wondering",
"are of the opinion that" => "believe",
"are presently" => "are now",
"aren't nearly" => "aren't",
"arrive at the conclusion" => "conclude",
"as a matter of fact" => "",
"as a means of" => "to",
"as a means to" => "to",
"as a while" => "",
"as far as i'm concerned" => "",
"as it truly is" => "",
"as of now" => "about",
"as the case may be" => "",
"ascertain" => "find out whether",
"ask the question" => "ask",
"assist" => "help",
"assistance" => "help",
"at about" => "at",
"at all times" => "always",
"at all times" => "",
"at an earlier stage" => "earlier",
"at first glance" => "",
"at the earliest possible date" => "as soon as possible",
"at the present time" => "now",
"at the same time that" => "while",
"at this time" => "now",
"attain" => "reach",
"attempt" => "try",
"attractive in appearance" => "attractive",
"augment" => "increase",
"basic fundamental" => "fundamental",
"basic fundamentals" => "fundamentals",
"basic necessity" => "need",
"basically" => "",
"be using" => "use",
"been pretty" => "been",
"best possible" => "best",
"biannually" => "twice a year",
"black in color" => "black",
"both of them" => "both",
"both of these" => "both",
"break apart" => "separate",
"brief in duration" => "brief",
"but the question remains:" => "",
"by and large" => "",
"by definition" => "",
"by leaps and bounds" => "",
"by means of" => "by",
"by means of" => "through",
"by virtue of the fact that" => "because",
"by virtue of" => "by",
"came to a realization" => "realized",
"came to an abrupt end" => "ended abruptedly",
"can be seen as" => "is",
"can potentially" => "can",
"can truly" => "can",
"carefully examines" => "examines",
"category" => "group",
"cease" => "stop",
"clearly evident" => "obvious",
"climb up" => "climb",
"close proximity" => "close",
"close scrutiny" => "scrutiny",
"cognizant" => "aware",
"combine together" => "combine",
"commence" => "start",
"common similarities" => "similarities",
"compare and contrast" => "compare",
"compeltely fulfilled" => "fulfilled",
"complete monopoly" => "monopoly",
"complete stranger" => "stranger",
"completely destroyed" => "destroyed",
"completely eliminate" => "eliminate",
"conceal" => "hide",
"concerning" => "about",
"concerting the matter of" => "",
"conduct an investigation into" => "investigate",
"consensus" => "agreement",
"consequently" => "so",
"considered to be" => "considered",
"consolidate" => "combine",
"construct" => "build",
"continue on" => "continue",
"contributing factor" => "cause",
"convincingly explains" => "explains",
"cooperate together" => "cooperate",
"cooperate" => "help",
"correctional facilities" => "jails",
"correctional facility" => "jail",
"costs a total of" => "costs",
"definitely" => "",
"demise" => "death",
"denote" => "mean",
"despite the fact that" => "although",
"did not succeed" => "failed",
"doctorate degree" => "doctorate",
"does get" => "gets",
"due to the effects" => "because",
"due to the fact that" => "because",
"during the course of" => "during",
"during the month of" => "in",
"e.g." => "for example",
"each and every" => "each",
"each and every" => "every",
"early, primitive" => "primitive",
"economically deprived" => "poor",
"eliminate" => "get rid of",
"encounter" => "meet",
"end product" => "product",
"end result" => "result",
"endeavor" => "try",
"enter into" => "enter",
"erode away" => "erode",
"especially vital" => "vital",
"essentially" => "",
"estimated at about" => "estimated",
"exact same" => "same",
"exactly how" => "how",
"exactly identical" => "identical",
"exactly the" => "the",
"except when" => "unless",
"excess verbiage" => "verbiage",
"excessive number of" => "too many",
"expedite" => "hasten",
"expend" => "spend",
"expenditure" => "cost",
"expenditures" => "costs",
"extend an invitation" => "invite",
"extremely" => "",
"facility" => "ease",
"far beyond" => "beyond",
"far, far beyond" => "beyond",
"far, far" => "far",
"feasible" => "possible",
"few in number" => "few",
"filled to capacity" => "filled",
"filled to the brim" => "filled",
"final completion" => "completion",
"final conclusion" => "conclusion",
"final demise" => "demise",
"final outcome" => "outcome",
"final result" => "result",
"final verdict" => "verdict",
"find out" => "find",
"first and foremost" => "first",
"first began" => "began",
"first created" => "created",
"first introduced" => "introduced",
"first invented" => "invented",
"follow after" => "after",
"foot pedal" => "pedal",
"for all intents and purposes" => "",
"for approximately" => "about",
"for that which is" => "for the",
"for the most part" => "",
"for the purpose of" => "for",
"foreign imports" => "imports",
"free gift" => "gift",
"fulfilled completely" => "fulfilled",
"full and complete" => "full",
"further explain" => "explain",
"future plans" => "plans",
"future prospects" => "prospects",
"gather together" => "gather",
"general consensus" => "consensus",
"general public" => "public",
"generally" => "",
"get an idea of" => "visualize",
"give consideration to" => "consider",
"give rise to" => "cause",
"given the fact that" => "because",
"go ahead and" => "",
"grave crisis" => "crisis",
"group together" => "group",
"hand-in-hand" => "together",
"happens to be" => "is",
"hardley" => "not",
"has a tendency to" => "tends to",
"have a tendency to" => "often",
"have an effect on" => "influence",
"having to do" => "doing",
"having to make" => "making",
"having to take" => "taking",
"hazardous" => "unsafe",
"he totally lacked the ability to" => "he couldn't",
"held a meeting" => "met",
"henceforth" => "from now on",
"hold a meeting" => "meet",
"honest truth" => "truth",
"horrible tragedy" => "tragedy",
"i also claim that" => "",
"i can guarantee that" => "",
"i can guarantee" => "",
"i claim that" => "",
"i find that" => "",
"i guess" => "",
"i know i've" => "I've",
"i might add" => "",
"i myself" => "I",
"i should also mention that" => "",
"i think that" => "",
"i think that," => "",
"i think" => "",
"i think," => "",
"i want to say that" => "",
"i wish to take this opportunity to" => "I want to",
"i'd also argue that" => "",
"i'd go so far as to say" => "",
"i'll just" => "I'll",
"i'm sure" => "",
"i.e." => "that is",
"if and when" => "if",
"illustrates" => "shows",
"immediate vicinity" => "vicinity",
"in a manner of speaking" => "",
"in a sense" => "",
"in a situation in which" => "in",
"in a very real sense" => "",
"in actuality" => "",
"in addition to" => "besides",
"in all likelyhood" => "likely",
"in an effort to" => "to",
"in close proximity" => "near",
"in color" => "",
"in colour" => "",
"in connection with" => "about",
"in essense" => "",
"in excess of" => "more than",
"in fact," => "",
"in lieu of" => "instead of",
"in light of the fact that" => "because",
"in my opinion" => "",
"in my opinion," => "",
"in nature" => "",
"in order to" => "to",
"in reality" => "",
"in regard to" => "as for",
"in spite of the fact that" => "although",
"in spite of" => "despite",
"in terms of" => "",
"in the area of" => "in",
"in the course of" => "during",
"in the course of" => "in",
"in the event that" => "if",
"in the final analysis" => "",
"in the final analysis," => "",
"in the process of" => "",
"in today's society" => "today",
"in truth," => "",
"in view of the fact that" => "because",
"in which" => "",
"inception" => "start",
"indication" => "sign",
"individuals" => "people",
"inform" => "tell",
"initiate" => "start",
"inner feelings" => "feelings",
"inquire" => "ask",
"insitute:verb" => "introduce",
"interestingly enough" => "",
"irregardless" => "",
"is able to" => "can",
"is aware of the fact that" => "knows",
"is found to be" => "is",
"is going to" => "will",
"is in conflict with" => "conflicts with",
"is in contrast with" => "contrasts with",
"is making" => "makes",
"is of significant importance" => "is important",
"is one reason why" => "is why",
"is presently" => "is now",
"is pretty darn" => "",
"is required" => "is needed",
"is scared of" => "fears",
"is seen as" => "is",
"is when" => "is",
"is where" => "",
"it almost seems like" => "",
"it can be seen that" => "",
"it does make" => "it makes",
"it does seem" => "it's",
"it goes to show that" => "",
"it is clear that" => "",
"it is evident that" => "",
"it is important to keep in mind that" => "",
"it is interesting to note that" => "",
"it is my opinion that" => "",
"it is possible that" => "",
"it is probably that" => "probably",
"it seems like" => "",
"it seems that" => "",
"it should be pointed out that" => "",
"it should be pointed out" => "",
"it's worth pointing out that" => "",
"join together" => "join",
"just a" => "a",
"just to" => "to",
"kind of" => "",
"large in size" => "large",
"last but not least" => "finally",
"last, but not least" => "finally",
"later on" => "later",
"link together" => "link",
"literally" => "",
"made a statement that" => "said that",
"made out of" => "made of",
"make a decision" => "decide",
"make an assumption" => "assume",
"make contact with" => "contact",
"make reference to" => "refer to",
"manner in which" => "way",
"manner" => "way",
"materialize" => "appear",
"may possibly" => "may",
"mental attitude" => "attitude",
"might possibly" => "might",
"might very well" => "may",
"minuscule" => "tiny",
"mitigate" => "reduce",
"mix together" => "mix",
"modifications" => "changes",
"modify" => "change",
"month after month" => "each month",
"month of September" => "September",
"more and more" => "often",
"more often than not" => "",
"more or less" => "",
"more preferable" => "preferable",
"more than a few" => "some",
"more than adequate" => "adequate",
"moreover" => "besides",
"mutual agreement" => "agreement",
"mutual communication" => "communication",
"mutual cooperation" => "cooperation",
"mutual friendship" => "friendship",
"mutual understanding" => "understanding",
"natural instinct" => "instinct",
"necessary prerequisite" => "prerequisite",
"necessity" => "need",
"never once" => "never",
"nevertheless" => "yet",
"new breakthrough" => "breakthrough",
"new development" => "development",
"new record" => "record",
"none at all" => "none",
"not been kind" => "been unkind",
"not dissimilar" => "like",
"not impossible" => "possible",
"not in a position to" => "can't",
"not infrequent" => "frequent",
"not infrequently" => "frequently",
"not many" => "few",
"not necessarily" => "not",
"not old enough" => "too young",
"not possible" => "impossible",
"not the same" => "different",
"not unlike" => "like",
"not unnoticed" => "noticed",
"now compare" => "compare",
"numerous" => "many",
"objective" => "goal",
"obtain" => "get",
"obviate" => "avoid",
"obviously" => "",
"occurred" => "happened",
"occurs" => "happens",
"of great importance" => "that's important",
"of major importance" => "that's important",
"often times" => "often",
"old cliche" => "cliche",
"old proverb" => "proberb",
"old relic" => "relic",
"on a daily basis" => "daily",
"on a daily basis" => "daily",
"on a day to day basis" => "daily",
"on a frequent basis" => "frequently",
"on a monthy basis" => "monthly",
"on a weekly basis" => "weekly",
"on a yearly basis" => "yearly",
"on the occasion of" => "on",
"on the whole" => "",
"on top of all of this" => "moreover",
"ongoing" => "continuing",
"only serves to" => "",
"opt for" => "choose",
"optimum" => "best",
"or alternatively" => "or",
"or, alternatively" => "or",
"or, say," => "",
"orientate" => "orient",
"over and over" => "repeatedly",
"overall goal" => "goal",
"overall plan" => "plan",
"overall structure" => "structure",
"owing to the fact that" => "because",
"particular type of" => "",
"particularly" => "",
"passing craze" => "craze",
"passing fancy" => "fancy",
"past experience" => "experience",
"past history" => "history",
"past memories" => "memories",
"perfectly legitimate" => "legitimate",
"period of time" => "period",
"permit:verb" => "allow",
"personal opinion" => "opinion",
"personal opinions" => "opinions",
"peruse" => "study",
"pin number" => "PIN",
"place:verb" => "put",
"plan ahead" => "plan",
"point in time" => "time",
"portion" => "part",
"possess" => "have",
"possibility" => "chance",
"postpone until later" => "postpone",
"potentially dangerous" => "dangerous",
"potentially hazardous" => "hazardous",
"pre-owned" => "used",
"preplan" => "plan",
"preplanning" => "planning",
"present incumbent" => "incumbent",
"present time" => "now",
"preserve" => "keep",
"pretty cool" => "cool",
"pretty important" => "important",
"prior history" => "history",
"prior to" => "before",
"probably occurred" => "occurred",
"probably true" => "true",
"probably won't" => "won't",
"proceed" => "continue",
"procure" => "get",
"provided that" => "if",
"providing that" => "provided",
"purchase:verb" => "buy",
"quite clearly" => "",
"quite" => "",
"rate of speed" => "speed",
"rather" => "",
"real life" => "life",
"real truth" => "truth",
"realize a savings of" => "save",
"really just" => "",
"really" => "",
"reason is because" => "reason is",
"reason why" => "why",
"reasonable expect" => "expect",
"reasonable substitute" => "substitute",
"reasonably well" => "well",
"receive" => "get",
"record high" => "record",
"rectangular in shape" => "rectangular",
"refer back" => "refer",
"refer to as" => "call",
"referred to as" => "called",
"referring back" => "referring",
"regardless of the fact that" => "although",
"remainder" => "rest",
"remunerate" => "pay",
"reoccur" => "recur",
"represents" => "is",
"request:verb" => "ask",
"retain" => "keep",
"retains" => "keeps",
"right up to the" => "to the",
"round in shape" => "round",
"safe haven" => "haven",
"seem to have" => "have",
"seem to me" => "seem",
"seemed to make" => "made",
"seemingly" => "",
"seems to have" => "has",
"select" => "choose",
"semiannually" => "twice a year",
"separate instances" => "instances",
"separate pieces" => "pieces",
"seriously need" => "need",
"simple and unsophisticated" => "simple",
"since left" => "left",
"small in size" => "small",
"smooth to the touch" => "smooth",
"some kind of" => "",
"somewhere in the neighbourhood of" => "about",
"sorely disappointed" => "disappointed",
"sort of" => "",
"sorts of" => "",
"specific highlights" => "highlights",
"square in shape" => "square",
"starve to death" => "starve",
"state:verb" => "say",
"still remains" => "remains",
"strategize" => "plan",
"study in depth" => "study",
"subsequent to" => "following",
"substantiate" => "back up",
"successfully obtains" => "obtains",
"sudden crisis" => "crisis",
"sufficient" => "enough",
"sum total" => "total",
"summon" => "call",
"supplement:verb" => "add to",
"symbolically represents" => "symbolizes",
"take a look" => "look",
"take action" => "act",
"take the time to" => "",
"tall in hight" => "tall",
"temporary loan" => "loan",
"tend to" => "",
"terminate" => "end",
"that being said" => "",
"that effectively" => "that",
"that exists" => "",
"that is to say" => "",
"the colour green" => "",
"the last point i would like to make is that" => "",
"the month of" => "",
"the point that i am trying to make is that" => "",
"the question as to whether" => "the question whether",
"the reason is because" => "the reason is",
"the way in which" => "the way",
"there appear to be" => "there are",
"therefore" => "so",
"they just" => "they",
"thing you'll need to do" => "step",
"through the use of" => "through",
"throughout the course of" => "throughout the",
"thus" => "so",
"to a further extent" => "further",
"to put it charitably" => "",
"took a solid" => "took",
"total abstinence" => "abstinence",
"total annihilation" => "annihilation",
"total number" => "number",
"total sum" => "total",
"totally obvious" => "obvious",
"totally" => "",
"true fact" => "fact",
"true facts" => "facts",
"try it out" => "try it",
"trying unsuccessfully" => "trying",
"type of" => "",
"typically" => "usually",
"unite together" => "unite",
"united as one" => "united",
"until such time as" => "until",
"usual habit" => "habit",
"utilize" => "use",
"utilized" => "used",
"utilizing" => "using",
"utmost perfection" => "perfection",
"utterly" => "",
"valuable asset" => "asset",
"various differences" => "differences",
"various different" => "various",
"very own" => "own",
"virtually" => "almost",
"vis-a-vis" => "compared with",
"visible to the eye" => "visible",
"warn in advance" => "warn",
"was a little" => "was",
"way more" => "more",
"we're using" => "we use",
"well aware of" => "aware",
"well, at least" => "at least",
"well," => "",
"went so far as to" => "",
"what i mean to say is that" => "",
"what i'm seeing is" => "I see",
"what is important is" => "",
"what is needed is" => "we need ",
"what it is is" => "it is",
"what they don't realize is" => "they don't realize",
"what we need is" => "we need",
"whatsoever" => "",
"when all is said and done" => "",
"while at the same time" => "while",
"with regard to" => "as for",
"with regard to" => "regarding",
"with the exception of" => "except for",
"witnessed first hand" => "witnessed",
"world we live in" => "world",
"you just have to" => "you have to",
"you might consider" => "consider",
"you should know about" => "",
"you're starting" => "you start"
]
